apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: rhte-api-pipeline
metadata:
  annotations:
    description: RHTE Deployment Pipeline
  name: rhte-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: rhte-pipeline
    name: rhte-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: ANSIBLE_TEST_INVENTORY
          value: ${ANSIBLE_TEST_INVENTORY}
        - name: ANSIBLE_PROD_INVENTORY
          value: ${ANSIBLE_PROD_INVENTORY}
        - name: ANSIBLE_JOB_TEMPLATE
          value: ${ANSIBLE_JOB_TEMPLATE}
        - name: ANSIBLE_TOWER_SERVER
          value: ${ANSIBLE_TOWER_SERVER}
        - name: OPENSHIFT_SERVICE_NAME
          value: ${OPENSHIFT_SERVICE_NAME}
        - name: OPENSHIFT_IMAGE_STREAM
          value: ${OPENSHIFT_IMAGE_STREAM}
        - name: OPENSHIFT_BUILD_CONFIG
          value: ${OPENSHIFT_BUILD_CONFIG}
        - name: OPENSHIFT_BUILD_PROJECT
          value: ${OPENSHIFT_BUILD_PROJECT}
        - name: OPENSHIFT_TEST_ENVIRONMENT
          value: ${OPENSHIFT_TEST_ENVIRONMENT}
        - name: OPENSHIFT_PROD_ENVIRONMENT
          value: ${OPENSHIFT_PROD_ENVIRONMENT}
        - name: OPENSHIFT_DEPLOYMENT_CONFIG
          value: ${OPENSHIFT_DEPLOYMENT_CONFIG}
        - name: MICROCKS_SERVER_URL
          value: ${MICROCKS_SERVER_URL}
        - name: MICROCKS_SERVICE_ID
          value: ${MICROCKS_SERVICE_ID}
        - name: MICROCKS_TEST_ENDPOINT
          value: ${MICROCKS_TEST_ENDPOINT}
parameters:
- name: GIT_REPO
  value: https://github.com/nmasse-itix/rhte-api.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: ANSIBLE_TEST_INVENTORY
  value: 3scale-test
  required: true
- name: ANSIBLE_PROD_INVENTORY
  value: 3scale-prod
  required: true
- name: ANSIBLE_JOB_TEMPLATE
  value: Deploy an API to 3scale
  required: true
- name: ANSIBLE_TOWER_SERVER
  value: tower
  required: true
- name: OPENSHIFT_SERVICE_NAME
  value: rhte-api
  required: true
- name: OPENSHIFT_IMAGE_STREAM
  value: rhte-api
  required: true
- name: OPENSHIFT_BUILD_CONFIG
  value: rhte-api
  required: true
- name: OPENSHIFT_BUILD_PROJECT
  value: rhte-build
  required: true
- name: OPENSHIFT_TEST_ENVIRONMENT
  value: rhte-test
  required: true
- name: OPENSHIFT_PROD_ENVIRONMENT
  value: rhte-prod
  required: true
- name: OPENSHIFT_DEPLOYMENT_CONFIG
  value: rhte-api
  required: true
- name: MICROCKS_SERVER_URL
  value: http://microcks:8080/api
  required: true
- name: MICROCKS_SERVICE_ID
  value: RHTE-API:1.1
  required: true
- name: MICROCKS_TEST_ENDPOINT
  required: true
